MODEL:
  META_ARCHITECTURE: "CenterNet"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  CENTERNET:
    NUM_CLASSES: 80
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    NUM_CONVS: 3
    FPN_STRIDES: [8, 16, 32, 64, 128]
    CAT_SPEC_WH: False
    PRIOR_PROB: 0.01
    HEAD_NORM: "GN"
#    SCORE_THRESH_TEST: 0.05
#    TOPK_CANDIDATES_TEST: 1000
#    NMS_THRESH_TEST: 0.6
#    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    FOCAL_LOSS_BETA: 4.0
    FOCAL_LOSS_ALPHA: 2.0
    BOX_REG_LOSS_TYPE: "smooth_l1"
#    CENTER_SAMPLING_RADIUS: 0.0
    OBJECT_SIZES_OF_INTEREST: [[-1, 64],[64, 128],[128, 256],[256, 512],[512, .inf],] # for size 800~1333
#    NORM_SYNC: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
