_BASE_: "Base-CenterNet-FPN.yaml"
MODEL:
#  WEIGHTS: "pretrained_weights/FCOS_imprv_R_50_FPN_1x.pth"
  RESNETS:
    NORM: "FrozenBN" # default
    DEPTH: 50 # default
  BACKBONE:
    FREEZE_AT: 3 # custom, freeze the first 3 Resnet stages so they are not trained
  CENTERNET:
    NUM_CLASSES: 1
    NUM_CONVS: 3
    CAT_SPEC_WH: True
    HEAD_NORM: "GN"
    IN_FEATURES: ["p3", "p4", "p5", "p6"]
    FOCAL_LOSS_BETA: 4.0
    FOCAL_LOSS_ALPHA: 2.0
    BOX_REG_LOSS_TYPE: "smooth_l1"
#    CENTER_SAMPLING_RADIUS: 1.5
#    OBJECT_SIZES_OF_INTEREST: [[-1, 64],[64, 128],[128, 256],[256, 512],[512, .inf],] # for size 800~1333
#    OBJECT_SIZES_OF_INTEREST: [[-1, 38],[38, 76],[76, 152],[152, 304],[304, .inf],] # for size 480
    OBJECT_SIZES_OF_INTEREST: [[-1, 38],[38, 76],[76, 152],[152, .inf],] # for size 480
#    NORM_SYNC: False
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 2
  BASE_LR: 0.01
INPUT:
#  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800) # default
#  MAX_SIZE_TRAIN: 1333 # default
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 480

OUTPUT_DIR: "./output/centernet_R_50_FPN_develop"
